"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
($directory)\
(\
[î‚°](fg:prev_bg bg:17)\ 
$git_branch\
$git_commit\
$git_status\
$git_state\
)\
(\
[î‚°](fg:prev_bg bg:black)\
[î‚°](fg:prev_bg bg:236)\
$docker_context\
)\
(\
[î‚°](fg:prev_bg bg:black)\
[î‚°](fg:prev_bg bg:236)\
$package\
)\
[î‚°](fg:prev_bg)\
(\
$rust\
$golang\
$c\
$java\
$kotlin\
$gradle\
$nodejs\
$deno\
$bun\
$python\
$conda\
$elixir\
$ruby\
$lua\
$typst\
$terraform\
$aws\
$gcloud\
$openstack\
$azure\
)\
$fill\
(\
[î‚²](bg:black fg:9)\
$status\
)\
[î‚²](bg:prev_bg fg:250)\
$time\
$line_break\
$character"""

[username]
show_always = true
style_user = "bg:250 fg:black"
style_root = "bg:250 fg:black"
format = '[ ï€‡ $user ]($style)'

[directory]
style = "bg:blue fg:black"
read_only_style = "bg:9 fg:226"
format = "([î‚°](fg:prev_bg bg:9)[ $read_only ]($read_only_style))[î‚°](fg:prev_bg bg:blue)[ ï¼  $path ]($style)"
truncation_length = 0
truncation_symbol = "â€¦/"
fish_style_pwd_dir_length = 0
read_only = "ï€£"

[git_branch]
symbol = "ï˜"
style = "bg:232 fg:169"
format = '[ $symbol $branch]($style)'

[git_commit]
style = "bg:232 fg:169"
format = '[ ï…²  $hash ]($style)'

[git_status]
style = "bg:232 fg:169"
# Different colors for `stashed` & the rest
# format = '[($stashed )([( $conflicted)( $deleted)( $renamed)( $modified)( $typechanged)( $staged)( $untracked)( $ahead_behind)](bg:148 fg:124))]($style)'
format = '[(( $ahead_behind)([ $stashed](bg:prev_bg fg:244))[( $conflicted)( $deleted)( $renamed)( $modified)( $typechanged)( $staged)( $untracked)](bg:prev_bg fg:11)) ]($style)'
conflicted = 'ï‰– '
untracked = 'ï„¨'
modified = 'ï„ª'
renamed = 'ï„'
deleted = 'âœ˜'
staged = 'ï§'
ahead = 'ï€› ${count}'
diverged = 'ï€› ${ahead_count} ï€š ${behind_count}'
behind = 'ï€š ${count}'
stashed = 'ï€œ ${count}'

[git_state]
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry-pick"
bisect = "bisect"
am_or_rebase = "AM/rebase"
style = "bold bg:232 fg:9"
format = '[| [$state( $progress_current/$progress_total)](bold italic fg:prev_fg bg:prev_bg) ]($style)'

[docker_context]
symbol = "ó°¡¨"
style = "bold bg:236 fg:31"
format = '[ $symbol( $context) ]($style)'

[package]
symbol = "ğŸ“¦ï¸"
style = "bg:236 fg:182"
format = '[ $symbol $version ]($style)'

[rust]
symbol = "ğŸ¦€"
style = "fg:yellow"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = "ó°Ÿ“"
style = "fg:blue"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = "î˜"
style = "fg:69"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = "î¶¯"
style = "fg:208"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = "ó±ˆ™"
style = "fg:purple"
format = '[ $symbol( $version) ]($style)'

[gradle]
symbol = "î™ "
style = "fg:30"
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = "ó°™"
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[deno]
symbol = "îŸ€"
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[bun]
symbol = "î¯"
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = "ó°Œ "
style = "fg:178"
format = '[ $symbol( $version) ]($style)'

[conda]
symbol = "îœ•"
style = "fg:148"
format = '[ $symbol( $environment) ]($style)'

[elixir]
symbol = "î˜­"
style = "fg:purple"
format = '[ $symbol( $version) ]($style)'

[ruby]
symbol = "ó°´­"
style = "fg:9"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = "îµ­ "
style = "fg:69"
format = '[ $symbol( $version) ]($style)'

[lua]
symbol = "ó°¢±"
style = "fg:69"
format = '[ $symbol( $version) ]($style)'

[typst]
symbol = "ï¿"
style = "fg:cyan"
format = '[ $symbol( $version) ]($style)'

[terraform]
symbol = "ó±¢"
style = "fg:purple"
format = '[ $symbol( $version) ]($style)'

[fill]
symbol = " "

[status]
disabled = false
style = "bold bg:9 fg:184"
format = '[ $common_meaning$signal_name$maybe_int $symbol ]($style)'
map_symbol = true
symbol = "âŒ"
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
sigint_symbol = "ó°Ÿ¾ "
signal_symbol = "âš¡"

[time]
disabled = false
time_format = "%T"
style = "bg:250 fg:black"
format = '[ $time ïº  ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:green)'
error_symbol = '[ï²](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_visual_symbol = '[ï´](bold fg:yellow)'

